// FOOTER
export const FOOTER_SET_TITLE = 'FOOTER_SET_TITLE';
export const FOOTER_SET_SUBTITLE = 'FOOTER_SET_SUBTITLE';
export const FOOTER_SET_DESCRIPTION = 'FOOTER_SET_DESCRIPTION';
export const FOOTER_SET_TABS = 'FOOTER_SET_TABS';

//TOURNAMENT PANEL
export const TOURNAMENT_PANEL_SET_IMAGE = 'TOURNAMENT_PANEL_SET_IMAGE';
export const TOURNAMENT_PANEL_SET_TITLE = 'TOURNAMENT_PANEL_SET_TITLE';
export const TOURNAMENT_PANEL_SET_FIRST_PLACE = 'TOURNAMENT_PANEL_SET_FIRST_PLACE';
export const TOURNAMENT_PANEL_SET_SECOND_PLACE = 'TOURNAMENT_PANEL_SET_SECOND_PLACE';
export const TOURNAMENT_PANEL_SET_THIRD_PLACE = 'TOURNAMENT_PANEL_SET_THIRD_PLACE';